# docker compose -p host-mvn -f compose.yaml up -d
# docker compose -p host-mvn down
# wget -c https://maven.reposilite.com/releases/com/reposilite/reposilite/3.5.18/reposilite-3.5.18-all.jar
# java -Xmx32M -Dreposilite.port=8089 -Dtinylog.writerFile.file=/dev/stdout
services:
  maven-reposilite:
    image: docker.io/eclipse-temurin:17-jre-focal
    hostname: maven-reposilite.dev
    container_name: maven-reposilite.dev
    environment:
      - TZ=Asia/Shanghai
    network_mode: host
    user: "1000:1000"
    volumes:
      - ./reposi:/app
    restart: always
    mem_limit: 512M
    memswap_limit: -1
    #shm_size: 1gb
    cpuset: '0'
    command:
      - java
      - -Xmx64M
      - -jar
      - -Dtinylog.writerFile.file=/dev/stdout
      - /app/reposilite-3.5.18-all.jar
      - --port=8089
      - -wd=/app/data
      - -t=dev:your-token-xxx

# test
# docker run --rm -itd -m 1g --name test-maven maven:3.8.5-eclipse-temurin-17
# mvn -s ~/new_reposi.xml dependency:get -Dartifact=com.common.utils:common-utils:2.3.9
