# docker compose -p host-mvn -f compose.yaml up -d
# docker compose -p host-mvn down
services:
  maven-reposilite:
    image: softlang/maven:reposilite2-java17
    hostname: maven-reposilite.dev
    container_name: maven-reposilite.dev
    environment:
      - TZ=Asia/Shanghai
    network_mode: host
    #user: "1000:1000"
    volumes:
      - ./data:/siri/app/data
    restart: always
    mem_limit: 512M
    memswap_limit: -1
    #shm_size: 1gb
    cpuset: '0'
    command:
      - exec
      - java
      - -Dtinylog.writerFile.file=/dev/stdout
      - -Dreposilite.proxied=https://maven.aliyun.com/repository/public
      - -Dreposilite.port=8080
      - -Xmx64M
      - -jar
      - v2reposilite.jar
      - -wd=data
# test
# mvn -s ~/settings.xml dependency:go-offline -f pom.xml
# mvn -s ~/settings.xml dependency:get -Dartifact=com.common.utils:common-utils:2.3.9
