# docker pull haproxy:lts-alpine
# docker stack deploy -c compose.yaml ns_dev
version: '3.7'
networks:
  default:
    name: ns_dev
    external: true

services:
  api-demo-whoami:
    image: ${IMAGE_NAME}
    #image: docker.io/traefik/whoami:v1.10
    hostname: ${BUILD_TAG}
    environment:
      TZ: Asia/Shanghai
    deploy:
      mode: replicated
      replicas: 1
      update_config:
        parallelism: 1
        delay: 20s
        #failure_action: rollback
        #order: start-first # default=stop-first
      resources:
        limits:
          cpus: '1'
          memory: 64M
      labels:
        - "io.portainer.accesscontrol.public"
        - "traefik.enable=true"
        - "traefik.http.services.whoami.loadbalancer.server.port=80"
        - "traefik.http.routers.whoami.rule=PathPrefix(`/api-demo-whoami`)"
        - "traefik.http.routers.whoami.entrypoints=dev"
        - "traefik.http.routers.whoami.service=api-demo-whoami"
