# docker pull haproxy:lts-alpine
# docker stack deploy -c compose.yaml ns_dev
# docs: https://github.com/docker/compose/tree/v1/docs
# https://github.com/docker/compose/blob/v1/docs/Compose%20file%20reference%20(legacy)/version-3.md
version: '3.7'
networks:
  default:
    name: ns_dev
    external: true

services:
  api-demo-whoami:
    image: ${IMAGE_NAME}
    #image: docker.io/traefik/whoami:v1.10
    hostname: ${BUILD_TAG}
    environment:
      TZ: Asia/Shanghai
    deploy:
      mode: replicated
      replicas: 1
      update_config:
        parallelism: 1
        delay: 5s
        #monitor: 300s \
        #order: start-first # default=stop-first
        #failure_action: rollback
      restart_policy:
        condition: on-failure
        delay: 10s
        #max_attempts: 3
        #window: 120s
      resources:
        limits:
          cpus: '1'
          memory: 64M
      labels:
        - "io.portainer.accesscontrol.public"
        - "traefik.enable=true"
        - "traefik.http.services.whoami.loadbalancer.server.port=80"
        - "traefik.http.routers.whoami.rule=PathPrefix(`/api-demo-whoami`)"
        - "traefik.http.routers.whoami.entrypoints=dev"
        - "traefik.http.routers.whoami.service=api-demo-whoami"
