# docker compose -p gpdb7 -f compose.yaml up -d
# docker compose -p gpdb7 down
# docker compose -f compose.yaml build
networks:
  default:
    name: apps
    external: true
services:
  gpdb7rhel8:
    #image: docker.io/oraclelinux:8
    image: localhost/gpdb7:rhel8
    build: 
      context: .
      dockerfile: ./Dockerfile
    hostname: gpdb7rhel8.local
    container_name: gpdb7rhel8.local
    restart: always
    environment:
       - TZ=Asia/Shanghai
    ports:
      - 5677:5677
    extra_hosts:
      - "gp7m1.local:127.0.0.1"
      - "gp7s1.local:127.0.0.1"
      - "gp7s2.local:127.0.0.1"
    #cpus: '2'
    cpuset: '0-1'
    mem_limit: 4gb
    memswap_limit: 4gb
    shm_size: 1gb
    volumes:
      - ./mpp/dist:/mpp/dist
      - ./mpp/pyops:/mpp/gpadmin/pyops
      - ./mpp/conf.d:/mpp/gpadmin/conf.d
    working_dir: /mpp
    command: /usr/sbin/sshd  -D -p22
