# 支持中文的postgresql-13.2 + citus 10.0.3
FROM citusdata/citus:10.0.3
RUN localedef -i zh_CN -c -f UTF-8 -A /usr/share/locale/locale.alias zh_CN.UTF-8

# mysql fdw
RUN apt-get update \
	&& apt-get install -y postgresql-13-mysql-fdw

RUN rm -rf /var/lib/apt/lists/* \
    && apt-get clean

ENV LANG zh_CN.utf8