# docker build --network host --force-rm -f Dockerfile.citus -t softlang/citus-cn:pg14v11fwd .
# 支持中文的postgresql-14.3 + citus 11.0.4
FROM citusdata/citus:11.0.4
RUN localedef -i zh_CN -c -f UTF-8 -A /usr/share/locale/locale.alias zh_CN.UTF-8
# mysql fdw
RUN apt-get update \
	&& apt-get install -y postgresql-14-mysql-fdw

RUN rm -rf /var/lib/apt/lists/* \
    && apt-get clean

ENV LANG zh_CN.utf8
