# my shell
# You may uncomment the following lines if you want `ls' to be colorized:
export LS_OPTIONS='--color=auto'
alias ls='ls $LS_OPTIONS'
alias ll='ls $LS_OPTIONS -l'
alias l='ls $LS_OPTIONS -lA'
#
# Some more alias to avoid making mistakes:
alias rm='rm -i'
alias cp='cp -i'
alias mv='mv -i'

# etcdctl
alias etcget='etcdctl --user=${etc_usr_get} get --limit=500 --prefix'
alias etcput='etcdctl --user=${etc_usr_set} put'
alias etcdel='etcdctl --user=${etc_usr_set} del'