# deb.debian.org
FROM quay.io/coreos/etcd:v3.4.18

ADD config.yaml /root/.etcd_confg.yaml
ADD compose.yaml /root/.etcd_compose.yaml
RUN apk update && apk add tzdata --no-cache && rm /var/cache/apk/ -rf

EXPOSE 2379 2380

CMD ["/usr/local/bin/etcd"]

# docker build --network host --force-rm -f Dockerfile.etcd -t etcd:v3.3.11 .
