# docker build --network host --force-rm -f Dockerfile -t softlang/mysqlrouter:v8.2 . 
FROM docker.io/oraclelinux:8

# arg rpm1="https://dev.mysql.com/get/mysql80-community-release-el8-9.noarch.rpm"
arg rpm2="https://dev.mysql.com/get/Downloads/MySQL-Shell/mysql-shell-8.2.1-1.el8.x86_64.rpm"
arg rpm3="https://dev.mysql.com/get/Downloads/MySQL-Router/mysql-router-community-8.2.0-1.el8.x86_64.rpm"
RUN dnf install -y python3 lsof $rpm2 $rpm3 && dnf clean all

CMD sh -c 'bash --norc'
# USER root
# docker run -itd --rm --name pgdb -e POSTGRES_PASSWORD=123654 softlang/postgres-cn:15.4
