# docker-compose -p bouncer4pg -f compose.yaml up -d
# docker-compose -p bouncer4pg down
version: "3.7"
networks:
  default:
    name: mpp
    external: true
services:
  bouncer4pg:
    image: softlang/pgbouncer:v1.17.0
    hostname: bouncer-for-pgdb
    container_name: bouncer-for-pgdb
    environment:
       - DB_USER=dev
       - DB_PASSWORD=123654
       - DB_HOST=127.0.0.1
       - DB_PORT=5432
       #- POOL_MODE=session
       - POOL_MODE=transaction
       - ADMIN_USERS=postgres,dev
       # - DB_NAME=test
    # network_mode: bridge
    ports:
      - "6432:6432"
    #cpu_count: 2
    cpuset: '0-1'
    mem_limit: 1gb
    memswap_limit: -1
    shm_size: 256mb