# https://github.com/pgvector/pgvector
# docker pull pgvector/pgvector:pg17
# docker compose -p pgvector -f compose.yaml up -d
# docker compose -p pgvector down
volumes:
  pgvecotr_data:
    name: pgvector_data
    driver: local
    driver_opts:
      type: none
      device: /data/moby/volumes/pgvector_data
      o: bind
services:
  pgvector-zyb:
    image: softlang/postgres-cn:16.8-pgvector
    #image: pgvector/pgvector:pg17
    hostname: pgvector17.local
    container_name: pgvector17.local
    environment:
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=xxx"
      - "POSTGRES_DB=app"
      - "TZ=Asia/Shanghai"
    volumes:
      - pgvecotr_data:/var/lib/postgresql/data:rw"
    network_mode: bridge
    #command: tail -f /dev/null
    cpus: '2'
    #cpuset: '0'
    mem_limit: 8gb
    memswap_limit: -1
    shm_size: 2gb
    ports:
     - 6932:5432
    restart: always