# 支持中文的postgresql-citus
# docker build --network host --force-rm -f Dockerfile.citus -t softlang/citus-cn:11.0.4 .
FROM citusdata/citus:11.0.4
RUN localedef -i zh_CN -c -f UTF-8 -A /usr/share/locale/locale.alias zh_CN.UTF-8
ENV LANG zh_CN.utf8
